#ifndef SPRITE_MANAGER_H_
#define SPRITE_MANAGER_H_

#include "raylib.h"
#include <stddef.h>

#define SPRITE_KITCHEN_TILE_1_ID 1
#define SPRITE_KITCHEN_TILE_2_ID 2
#define SPRITE_KITCHEN_TILE_3_ID 3
#define SPRITE_KITCHEN_TILE_4_ID 4
#define SPRITE_KITCHEN_TILE_5_ID 5
#define SPRITE_BRICK_TILE_ID 6
#define SPRITE_STONE_BRICK_TILE_ID 7
#define SPRITE_AZUL_TILE_1_ID 8
#define SPRITE_AZUL_TILE_2_ID 9
#define SPRITE_WOODEN_TILE_1_ID 10
#define SPRITE_WOODEN_TILE_2_ID 11
#define SPRITE_WOODEN_TILE_3_ID 12

#define SPRITE_ANCHOR1_ID 40
#define SPRITE_ANCHOR2_ID 41
#define SPRITE_ANCHOR3_ID 42

#define SPRITE_CABLE_LENGTH_ID 51
#define SPRITE_IMPORTANT_HAT_ID 52
#define SPRITE_IMPORTANT_HATL_ID 53
#define SPRITE_TELEVISION_ON_ID 54
#define SPRITE_TELEVISION_OFF_ID 55
#define SPRITE_BLENDER_OFF_STAGE1_ID 56
#define SPRITE_BLENDER_ON_STAGE1_ID 57
#define SPRITE_BLENDER_ON_STAGE2_ID 58
#define SPRITE_WASHING_MACHINE_OFF_ID 59
#define SPRITE_WASHING_MACHINE_ON_ID 60
#define SPRITE_TOOL_ID 62
#define SPRITE_SAFETY_HAT_ID 63
#define SPRITE_SAFETY_HATL_ID 64
#define SPRITE_BLENDER_OFF_STAGE2_ID 65
#define SPRITE_CHEF_HAT_ID 66
#define SPRITE_KING_HAT_ID 67
#define SPRITE_POINTY_HAT_ID 68
#define SPRITE_POINTY_HATL_ID 69
#define SPRITE_TOP_HAT_ID 70
#define SPRITE_BRICK_BACKGROUND_ID 71
#define SPRITE_FLOWER_BACKGROUND_ID 72
#define SPRITE_THOUGHT_CLOUD_ID 73
#define SPRITE_DIAMONDS_BACKGROUND_ID 74
#define SPRITE_CLUBS_BACKGROUND_ID 75
#define SPRITE_SPADES_BACKGROUND_ID 76
#define SPRITE_HEARTS_BACKGROUND_ID 77
#define SPRITE_POKER_BACKGROUND_ID 78
#define SPRITE_CONTROLS_INGAME_ID 79
#define SPRITE_WOOD_BACKGROUND_ID 80
#define SPRITE_LAMP_OFF_ID 81
#define SPRITE_LAMP_ON_STAGE1_ID 82
#define SPRITE_LAMP_ON_STAGE2_ID 83
#define SPRITE_CLOCK_OFF_ID 84
#define SPRITE_CLOCK_ON_ID 85
#define SPRITE_SWITCH_OFF_ID 86
#define SPRITE_SWITCH_ON_STAGE1_ID 87
#define SPRITE_SWITCH_ON_STAGE2_ID 88

#define SOUND_TRACK_STAPLE_ID 0
#define SOUND_TRACK_STAPLE_REMOVE_ID 1
#define SOUND_TRACK_INTRO_EFFECT_ID 2
#define SOUND_TRACK_JUMP_EFFECT_ID 3
#define SOUND_TRACK_PTERODACTYL_ID 4
#define SOUND_TRACK_ERROR_EFFECT_ID 5
#define SOUND_TRACK_WASHING_MACHINE_ID 6
#define SOUND_TRACK_BLENDER_ID 7
#define SOUND_TRACK_TELEVISION_ID 8

void initializeAssets();

void destroyAssets();

Texture2D getSpriteFromID(size_t SpriteID);
Sound getSoundTrackFromID(size_t MusicID);

size_t getMaxSprites();
size_t getMaxMusicTracks();

#endif // SPRITE_MANAGER_H_
